refactor:  update the sveltekit embed recipes
gofiber/recipes pull request #1731
Opened 2023-07-18 13:22 UTC by ugurkorkmaz

Hi, I have updated the Sveltekit Embed Recipes. Could you please review my PR?
Issue(#1399 )

2023-07-19 11:25 UTC, gaby requested changes

2023-07-19 11:25 UTC, gaby commented on sveltekit-embed/bin/exec.go
> +package main
This file should be a Makefile 😂

2023-07-19 11:25 UTC, gaby commented on sveltekit-embed/go.mod
> +	github.com/gofiber/fiber/v2 v2.47.0
Fiber v2.48.0 is the current latest

2023-07-19 12:56 UTC, ugurkorkmaz commented on sveltekit-embed/go.mod
> +	github.com/gofiber/fiber/v2 v2.47.0
I updated it.

2023-07-19 13:29 UTC, gaby approved these changes
LGTM

2023-07-22 15:58 UTC, efectn approved these changes

2023-07-24 05:49 UTC, ReneWerner87 commented on .github/dependabot.yml
> +    directory: "/entgo-sveltekit/template"
wrong directory

2023-07-24 05:52 UTC, ReneWerner87 approved these changes

2023-07-24 05:55 UTC, merged