Add dependabot support to each recipe
gofiber/recipes pull request #187
Opened 2022-08-13 22:48 UTC by gaby

### What this PR fixes:

Currently dependabot can't update dependencies recursively as stated here: https://github.com/dependabot/dependabot-core/issues/2178 https://github.com/dependabot/dependabot-core/issues/2824

This PR adds each directory to dependabot.yml so the go dependencies get updated. 

### Related issue:
Fixes #171 

### How to replicate:

* Git clone this repo: `git clone git@github.com:gofiber/recipes.git`
* Run the following script `python3 create_dependabot.py`

```python3
import os

pwd = os.getcwd()
print(f"Current working directory: {pwd}")

dirs = [entry.name for entry in os.scandir(os.path.join(pwd, "recipes")) if entry.is_dir()]

for entry in dirs:
    print('  - package-ecosystem: "gomod"')
    print(f'    directory: "/{entry}"')
    print('    schedule:')
    print('      interval: "daily"')
```

2022-08-14 09:30 UTC, efectn requested changes

2022-08-14 09:30 UTC, efectn commented on .github/dependabot.yml
> +    directory: "/.git"
Remove

2022-08-14 09:30 UTC, efectn commented on .github/dependabot.yml
> +    directory: "/.github"
Remove

2022-08-14 11:52 UTC, gaby commented on .github/dependabot.yml
> +    directory: "/.git"
Done

2022-08-14 11:52 UTC, gaby commented on .github/dependabot.yml
> +    directory: "/.github"
Done

2022-08-14 16:08 UTC, gaby commented
I was thinking about ordering the file by folder name. The other idea I had was adding the go.mod files for the folders than dont't have one. Thoughts?

2022-08-15 14:03 UTC, efectn approved these changes

2022-08-17 13:02 UTC, gaby commented
@ReneWerner87 When you get a chance, can you take a look at this? :-)

2022-08-17 13:02 UTC, ReneWerner87 commented
Sure

2022-08-17 13:04 UTC, merged