feat: add csrf-with-session example
gofiber/recipes pull request #2133
Opened 2023-10-14 20:01 UTC by sixcolors

Adds example for csrf with session.

2023-10-15 13:51 UTC, gaby requested changes

2023-10-15 13:51 UTC, gaby commented on csrf-with-session/README.md
> +## Token Lyfecycle
Typo here: Lifecycle

2023-10-15 13:51 UTC, gaby commented on csrf-with-session/README.md
> +It is important that CSRF tokens do not presist beyond the scope of the user's session, that a new session is created when the user logs in, and that the session is destroyed when the user logs out.
Persist

2023-10-15 16:02 UTC, sixcolors commented on csrf-with-session/README.md
> +## Token Lyfecycle
fixed, thx

2023-10-15 16:02 UTC, sixcolors commented on csrf-with-session/README.md
> +It is important that CSRF tokens do not presist beyond the scope of the user's session, that a new session is created when the user logs in, and that the session is destroyed when the user logs out.
fixed, thx again :)

2023-10-16 12:28 UTC, gaby approved these changes

2023-10-16 13:01 UTC, merged