fix(Recipes): auth-jwt-login bug not returning nil if user not found
gofiber/recipes pull request #2221
Opened 2024-01-21 09:47 UTC by yogenpoonudurai

**Why?** 

Instead of returning "User not found", "Invalid password" is displayed when calling `getUserByEmail` or `getUserByUsername` and the user is not found in the database.

**What?**

This PR updates the database query in the `getUserByEmail` and `getUserByUsername` to use First() instead of Find() when looking up a single user record. 

**Tests:**
 

<img width="442" alt="Screenshot 2024-01-21 at 5 44 57 PM" src="https://github.com/gofiber/recipes/assets/54759476/d59852ae-2071-4fbc-99a3-9f984764b441">

<img width="507" alt="Screenshot 2024-01-21 at 5 45 06 PM" src="https://github.com/gofiber/recipes/assets/54759476/34490d92-7863-4b54-9bc9-35caff2b5052">

2024-01-29 16:19 UTC, sixcolors requested changes
it’s not a best practice to return the existence of an account in a login function. 

https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html#authentication-responses

```text
Using any of the authentication mechanisms (login, password reset, or password recovery), an application must respond with a generic error message regardless of whether:

The user ID or password was incorrect.
The account does not exist.
The account is locked or disabled.
The account registration feature should also be taken into consideration, and the same approach of a generic error message can be applied regarding the case in which the user exists.

The objective is to prevent the creation of a [discrepancy factor](https://cwe.mitre.org/data/definitions/204.html), allowing an attacker to mount a user enumeration action against the application.
```

2024-01-29 16:24 UTC, sixcolors requested changes
Login functions should also work in constant time regardless of the account existence and should also use a constant time hash verification function.

https://en.m.wikipedia.org/wiki/Timing_attack

2024-02-21 21:38 UTC, ReneWerner87 commented
@yogenpoonudurai thx for the effort and PR, can you check the last hints

2024-02-27 07:35 UTC, yogenpoonudurai commented
Ok, will do.

2024-03-24 13:54 UTC, gaby commented
Ping @yogenpoonudurai

2024-04-04 04:23 UTC, yogenpoonudurai commented
Sorry guys. Missed this. Seems like this has been fixed in #2242. Closing this.

2024-04-04 04:23 UTC, closed without merging