add firebase functions example
gofiber/recipes pull request #2225
Opened 2024-02-10 08:00 UTC by kemalturk

2024-02-12 07:24 UTC, ReneWerner87 commented on firebase-functions/README.md
> +https://medium.com/@kmltrk07/how-to-deploy-gofiber-app-to-firebase-functions-8d4d537a4464
can you add a bit more, a short description of the example

please also link in the root readme

2024-02-12 07:26 UTC, ReneWerner87 requested changes
thx, we need some little adjustments

2024-02-12 07:26 UTC, ReneWerner87 commented on firebase-functions/src/database/database.go
> +	data := map[string]interface{}{
add this part as an instruction in the readme.md

2024-02-12 07:46 UTC, ReneWerner87 commented
@kemalturk

2024-02-18 20:08 UTC, kemalturk commented
@ReneWerner87 I've added detailed documentation to readme. If you have any suggestions or would like to make changes, please feel free to let me know.

2024-02-21 21:35 UTC, ReneWerner87 commented
@kemalturk thx, just the link in the root README.md is missing

can you do this https://github.com/gofiber/recipes/blob/master/README.md (alphabetical sorting)

2024-02-23 19:04 UTC, kemalturk commented
@ReneWerner87 Done! I've added the missing link to the root README.md

2024-02-23 19:05 UTC, merged