Add Vercel recipie
gofiber/recipes pull request #542
Opened 2022-10-15 15:43 UTC by AchoArnold

Add the ability to run go fiber as a serverless app on vercel.

2022-10-17 02:08 UTC, gaby requested changes

2022-10-17 17:06 UTC, AchoArnold commented on vercel/README.md
> +Make sure to add the `vercel.json` file so the routing will work properly with vercel. This will rewrite all requests to the application to the `api/index.go` handler where where the router will take
Fixed

2022-10-18 00:38 UTC, gaby approved these changes
Thanks!

2022-10-18 00:38 UTC, gaby commented
CC @ReneWerner87 @efectn

2022-10-18 00:39 UTC, gaby commented
@AchoArnold Can you add an entry under .github/dependabot.yml file. That way go.mod gets updated automatically.

2022-10-18 09:05 UTC, ReneWerner87 commented
- [ ] add an entry under .github/dependabot.yml file

2022-10-18 14:58 UTC, AchoArnold commented
Done @gaby , @ReneWerner87

2022-10-18 15:05 UTC, ReneWerner87 approved these changes

2022-10-18 15:06 UTC, merged